import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';


const styles = StyleSheet.create({
  rootContainer: {
    flex:1,
    backgroundColor:'white',
  },
  mainContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: 'center',
    borderBottomWidth: 0.2,
    borderColor: 'grey',
  },
  goBackIcon:{
   justifyContent:'center',
   height:hp('3%'),
   width:wp('12%'),
  },

  cartItem: {
    height: hp('14.5%'),
    justifyContent: 'space-between',
    marginVertical: hp('2%'),
    marginHorizontal:hp('2%'),
  },

  InnerCartItem:{
    flexDirection: 'row',
    alignItems: 'center' ,
  },
  imageIcon: {
    justifyContent:'center',
    alignItems:'center',
    height: hp('8%'),
    width: wp('18.6666667%'),
    backgroundColor: '#F6F6F6',
    borderRadius:5,
  },
  innerImage:{
    height:65,
    width:65,
  },
  ItemNameContainer:{
    paddingLeft: 15,
  },
  itemName: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 15.6,
    textAlign: 'left',
    color: 'black',
  },
  itemPrice: {
    fontFamily: 'Inter',
    fontSize: 16,
    paddingTop: hp('1%'),
    fontWeight: '600',
    lineHeight: 15.6,
    textAlign: 'left',
    color: '#686868',
  },
  quantityTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: hp('5%'),
  },
  quantityControl: {
    flexDirection: 'row',
    width: wp('45%'),
    justifyContent: 'space-between',
  },
  quantityButton: {
    borderRadius: 7,
    width: wp('12%'),
    backgroundColor: '#FEF2EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    fontSize: 30,
    color: '#F15927',
  },
  quantityshow: {
    width: wp('16%'),
    borderWidth: 1,
    borderRadius: 7,
    borderColor: '#C4C4C4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityText: {
    fontSize: 18,
    fontWeight: '500',
    alignItems: 'center',
    justifyContent: 'center',
    color:'black',
  },
  itemTotal: {
    width: wp('28%'),
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    alignContent:'flex-end',
  },
  itemTotaltext: {
    color:'#686868',
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 15.6,
    textAlign: 'right',
  },
  totalItemPrice: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 15.6,
    letterSpacing: -0.15,
    textAlign: 'right',
    color:'black',
  },
  removeItemView: {
    height: hp('3.5%'),
    width: '8%',
    marginTop: hp('0.7%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeButton: {
    color: '#F15927',
    fontSize: 16,
    fontWeight: '700',
  },
  couponContainer: {
    marginHorizontal:hp('2%'),
    height: hp('7%'),
    marginTop:hp('2%'),
    borderStyle: 'dashed',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#C4C4C4',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    marginBottom:hp('3.5%'),
  },
  coupanDetails: {
    width: wp('65%'),
    height: hp('6%'),
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    justifyContent: 'center',
  },
  coupanName: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 18,
    letterSpacing: -0.1,
    textAlign: 'left',
    color:'black',
  },
  InnerCoupanText:{
    color: '#C4C4C4',
    fontSize: 16 ,
  },
  removeText:{
    fontFamily: 'Inter',
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    letterSpacing: 0.21,
    textAlign: 'left',
    color:'#F15927',
  },

  summaryContainer: {
     marginHorizontal:hp('2%'),
     marginBottom:hp('1%'),
  },
  summaryText:{
    flexDirection:'row',
    justifyContent:'space-between',
  },

  summaryTextBorder:{
    borderTopWidth: 1,
    borderTopColor: '#C4C4C4',
    borderStyle: 'dashed',
  },
  subTotaltext:{
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 15.6,
    textAlign: 'left',
    color:'#1D1D1D',
    marginBottom:hp('1%'),
  },
  shipingText:{
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 15.6,
    textAlign: 'left',
    color:'#686868',
    marginBottom:hp('1%'),
  },
   totalAmount:{
    marginTop:hp('1.5%'),
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 16.94,
    letterSpacing: -0.15,
    textAlign: 'right',
    color:'black',
   },
   checkout:{
    borderTopWidth:1,
    borderTopColor:'#E6E6E6',
    height: hp('7%'),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp('2%'),
    marginTop: 'auto',
   },
   checkoutButton: {
    backgroundColor: '#F15927',
    alignItems: 'center',
    borderRadius: 8,
    height: hp('4.5%'),
    width: wp('35%'),
    justifyContent: 'center',
    marginRight:wp('2%'),

  },
  payingAmount:{
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22.61,
    letterSpacing: -0.1,
    textAlign: 'left',
    color:'black',
    marginLeft:wp('2%'),
  },
  checkoutText: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22.61,
    letterSpacing: -0.1,
    textAlign: 'left',
    color:'white',
  },
  disabledButton: {
    backgroundColor: '#ddd',
  },

  text: {
    fontSize: 20,
    marginLeft: wp('2.5%'),
    paddingHorizontal: 20,
    fontWeight: '400',
    color: 'black',
  },
});
export default styles;
