
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download


COPY . .

RUN go build -o /app/main .


FROM alpine:latest
WORKDIR /app


COPY --from=builder /app .


EXPOSE 8083


CMD ["/app/main"]


