import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  mainContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: 'center',
    borderBottomWidth: 0.2,
    borderColor: 'grey',
  },
  goBackIcon:{
    justifyContent:'center',
    height:hp('3%'),
    width:wp('12%'),
   },
  text: {
    fontSize: 20,
    marginLeft: wp('2.5%'),
    paddingHorizontal: 20,
    fontWeight: '400',
    color: 'black',
  },
  container: {
    flex: 1,
    paddingTop: hp('1.5%'),
    paddingHorizontal: wp('4.4%'),
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  productContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    padding: 10,
    borderRadius: 5,
  },
  imageIcon: {
    height: hp('8%'),
    justifyContent:'center',
    alignItems:'center',
    width: wp('18.6666667%'),
    backgroundColor: '#F6F6F6',
    borderRadius: 5,
  },
  innerImage:{
    height:hp('7%'),
    width:wp('12%'),
  },
  itemDetails: {
    marginLeft: wp('2%'),
    width: wp('20%'),
  },
  totalItems: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 24.5,
    letterSpacing: -0.15,
    textAlign: 'left',
    color: 'black',
  },
  showDetail: {
    color:'#686868',
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 15.6,
    textAlign: 'left',
  },
  totalBill: {
    flexDirection: 'row',
    width: hp('20%'),
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  ruppeeSymbol: {
    color:'#686868',
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21.28,
    letterSpacing: -0.11,
    textAlign: 'right',
  },
  totalPrice: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21.28,
    letterSpacing: -0.11,
    textAlign: 'right',
    color: 'black',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: hp('7%'),
  },
  headerText: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: hp('2.5%'),
    letterSpacing: -0.15,
    textAlign: 'left',
    marginVertical: wp('4.4%'),
    marginLeft: wp('2.5%'),
    color: 'black',
  },
  addressContainer: {
    padding: 8,
    backgroundColor: '#FAFAFA',
    marginBottom: 14,
    borderRadius: 8,
    borderColor: '#FAFAFA',
    borderWidth: 1,
  },
  totalPriceContainer:{
    alignItems: 'center' ,
    flexDirection: 'row',
  },
  selectedAddress: {
    backgroundColor: '#FEF2EE',
    borderColor: '#F15927',
    borderWidth: 1,
  },
  addressContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addressTextContainer: {
    flex: 1,
  },
  addressLabel: {
    color:'#686868',
    fontSize: 16,
    fontWeight: 'bold',
  },
  addressText: {
    color:'#686868',
    marginTop: 4,
  },
  tickMark: {
    fontSize: 20,
    color: '#ff6600',
  },
  continueButton: {
    backgroundColor: '#F15927',
    alignItems: 'center',
    borderRadius: 8,
    height: hp('4.5%'),
    width: wp('35%'),
    justifyContent: 'center',
    marginRight: wp('2%'),
  },
  continueButtonText: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22.61,
    letterSpacing: -0.1,
    textAlign: 'left',
    color: 'white',
  },
  disabledButton: {
    backgroundColor: '#ddd',
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: '#C4C4C4',
    height: hp('7%'),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp('4%'),
    marginBottom: 0,
    marginTop:'auto',
  },
});

export default styles;
