import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
const styles = StyleSheet.create({
    rootContainer: {
      flex: 1,
      paddingHorizontal: hp('2.5%'),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor:'rgba(0, 0, 0, 0.5)',
    },
    container: {
      width: wp('95%'),
      height: hp('26.5%'),
      backgroundColor: 'white',
      borderRadius: 8,
      elevation: 3,
    },
    innerImage:{
      height:hp('7%'),
      width:wp('14%'),
    },
    headerContainer: {
      height: hp('6.75%'),
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#E3E3E3',
      justifyContent: 'space-between',
      paddingHorizontal: hp('2%'),
    },
    header: {
      fontFamily: 'Inter',
      fontWeight: '500',
      fontSize: 20,
      lineHeight: 21,
      letterSpacing: -0.1,
      color: '#000',
    },
    itemContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      height: hp('8.5%'),
      width: wp('90%'),
      marginVertical: hp('2%'),
      paddingHorizontal: wp('2%'),
    },
    image: {
      width: wp('18%'),
      height: hp('8.5%'),
      justifyContent: 'center',
      alignItems:'center',
      backgroundColor: '#F6F6F6',
      borderRadius: 2,
    },
    detailsContainer: {
      flex: 1,
      justifyContent: 'space-between',
      marginLeft: wp('3%'),
    },
    itemTitle: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '400',
      textAlign: 'left',
      color: '#1D1D1D',
    },
    totalPrice: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 18,
      letterSpacing: -0.09,
      textAlign: 'right',
      color: '#1D1D1D',
    },
    buttonContainer: {
      marginTop: hp('1%'),
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    viewCartButton: {
      width: wp('43%'),
      height: hp('5.5%'),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#E99D84',
    },
    checkoutButton: {
      width: wp('43%'),
      height: hp('5.5%'),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 5,
      backgroundColor: '#F15927',
    },
    buttonText: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 26,
      letterSpacing: 0.21,
    },
  });
  export default styles;
